paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: virtuacreative
permalink: /:title.html
timezone: America/Sao_Paulo

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Virtua Creative Blog

description: Virtua Creative Blog
fb_description: Tutoriais e dicas para desenvolvimento de websites, web design e artes gráficas.
meta_keywords: blog, tutoriais, tutorials, jekyll, github, sass, html5, php, websites, web development, web design, artes gráficas, dreamweaver, criação de websites
share_image: http://goo.gl/JsefHX
logo_image: http://goo.gl/mXXyFH
fb_app:
  namespace: virtuacreative
  app_id: 1634907943429790
  app_admin: 100000561118294
author:
  name: VirtuaCreative
  email: info@virtuacreative.com.br
  github: VirtuaCreative
  twitter: virtuacreative
  flickr: virtuacreative
  linkedin:
  facebook: virtuacreative
  googleplus: VirtuacreativeBrWebsites/
  bio: Virtua Creative Technology
  email_md5: 6fa7e8a0b8a820fa63c7cfd1833b1be4 # gravatar

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
copyright_path: copyright.html

kramdown:
  input: GFM

gems:
  - jemoji
  - jekyll-mentions

baseurl: http://blog.virtuacreative.com.br
