baseurl: http://blog.virtuacreative.com.br
paginate: 10 # pagination based on number of posts
paginate_path: "page:num/"
exclude: ["README.md"] # files to exclude
disqus: virtuacreative # blog post comments
permalink: /:title.html
timezone: America/Sao_Paulo
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-paginate

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
copyright_path: copyright.html

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Virtua Creative Blog

description: Virtua Creative Blog
fb_description: "Tutoriais e dicas para desenvolvimento de websites, web design e artes gráficas."
meta_keywords: blog, tutoriais, tutorials, jekyll, github, sass, html5, php, websites, web development, web design, artes gráficas, dreamweaver, criação de websites
share_image: http://blog.virtuacreative.com.br/assets/media/fb_feed1200x630_virtua.png # FB e Twitter feed
logo_image: http://goo.gl/mXXyFH # logo sidebar
organization:
  name: Virtua Creative Technology
  url: http://www.virtuacreative.com.br
  logo: http://virtuacreative.com.br/images/LOGO-virtuacreative-60x72-gray.png # http://goo.gl/XzUou0
  logo_width: 72px
  logo_height: 60px
fb_app:
  namespace: virtuacreative
  app_id: 1634907943429790
  app_admin: 100000561118294
author:
  name: VirtuaCreative
  email: info@virtuacreative.com.br
  github: VirtuaCreative
  twitter: virtuacreative
  flickr: virtuacreative
  linkedin:
  facebook: virtuacreative
  googleplus: VirtuacreativeBrWebsites/ # DO NOT REMOVE - schema tags
  youtube: VirtuacreativeBrWebsites # DO NOT REMOVE - schema tags
  bio: Virtua Creative Technology
  email_md5: 6fa7e8a0b8a820fa63c7cfd1833b1be4 # gravatar
