paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: virtuacreative
permalink: /:title.html

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Virtua Creative Blog

description: Virtua Creative Blog
author:
  name: VirtuaCreative
  email: info@virtuacreative.com
  github: VirtuaCreative
  twitter: virtuacreative
  flickr: virtuacreative
  linkedin:
  facebook: virtuacreative
  googleplus: VirtuacreativeBrWebsites/posts
  bio: Virtua Creative Technology
  email_md5: 6fa7e8a0b8a820fa63c7cfd1833b1be4

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

kramdown:
  input: GFM

gems:
  - jemoji
  - jekyll-mentions

BASE_PATH: #http://virtuacreative.github.io/blog